import numpy as np
ifrom mport LinearRegression

create an array
a=np.array([1,2,3,4,5,6,7])
print(a)

In [3]:
type(a)

numpy.ndarray

In [4]:
# return a tuple with dimensions
a.shape

(7,)

In [6]:
# total number of elements
a.size

7

In [8]:
# reshape
b=np.arange(1,26,1).reshape(5,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
# slicing
# print
# 7 8 9
# 12 13 14
print(b[1:3 ,1:4])

[[ 7  8  9]
 [12 13 14]]


In [16]:
# find which number is greater than 12
b>12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [19]:
# return numbers
b[b>12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [33]:
# condition in array
# np.where(conditon,retun this if true   ,   else return when it false)
c=np.array([[13,-3,-5],[-2,12,99]])

np.where(c>0,c,-1)

array([[13, -1, -1],
       [-1, 12, 99]])

In [ ]:
# return indexes arrray(rows), array(column)
c=np.array([[13,-3,-5],[-2,12,99]])
np.where(c>0)

In [49]:
# not understood
arr=np.array([2,1,3])
# print(np.mean(arr))
np.percentile(arr,50)

2.0